plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.1'  // instead of 4.0.1
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.mak'
version = '0.0.1-SNAPSHOT'
description = 'Delivery module for the DM app'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation project(':dm-contracts')
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	runtimeOnly 'org.postgresql:postgresql'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
