server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dmdb
    username: dm
    password: dm

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: Asia/Kolkata

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topics:
      messageCreated: messages.created
